import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Provider } from "@/components/ui/provider";
import Navbar from "@/components/navbar";
import { Dancing_Script, Martian_Mono } from "next/font/google";

const martianMono = Martian_Mono({
  subsets: ["latin"],
})

const dancingScript = Dancing_Script({
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${martianMono.className}`}>
        <Provider>
          <Navbar></Navbar>
          {children}
        </Provider>
      </body>
    </html>
  );
}
